from PySide2.QtCore import QCoreApplication, QMetaObject, QSize
from PySide2.QtGui import QIcon
from PySide2.QtWidgets import QAbstractItemView, QFormLayout, QGridLayout, QGroupBox, QHBoxLayout, QHeaderView, QLabel, QLineEdit, QPushButton, QSpinBox, QStatusBar, QTableWidget, QWidget


class Ui_BatchRenameWindow(object):
    def setupUi(self, BatchRenameWindow):
        if not BatchRenameWindow.objectName():
            BatchRenameWindow.setObjectName(u"BatchRenameWindow")
        BatchRenameWindow.resize(980, 720)
        icon = QIcon()
        icon.addFile(u":/tool_icon/resource/main.png", QSize(), QIcon.Normal, QIcon.Off)
        BatchRenameWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(BatchRenameWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.folder_group = QGroupBox(self.centralwidget)
        self.folder_group.setObjectName(u"folder_group")
        self.folderLayout = QHBoxLayout(self.folder_group)
        self.folderLayout.setObjectName(u"folderLayout")
        self.folder_path = QLineEdit(self.folder_group)
        self.folder_path.setObjectName(u"folder_path")
        self.select_folder = QPushButton(self.folder_group)
        self.select_folder.setObjectName(u"select_folder")
        self.folderLayout.addWidget(self.folder_path)
        self.folderLayout.addWidget(self.select_folder)
        self.rule_group = QGroupBox(self.centralwidget)
        self.rule_group.setObjectName(u"rule_group")
        self.ruleLayout = QFormLayout(self.rule_group)
        self.ruleLayout.setObjectName(u"ruleLayout")
        self.prefix_label = QLabel(self.rule_group)
        self.prefix_label.setObjectName(u"prefix_label")
        self.prefix = QLineEdit(self.rule_group)
        self.prefix.setObjectName(u"prefix")
        self.start_index_label = QLabel(self.rule_group)
        self.start_index_label.setObjectName(u"start_index_label")
        self.start_index = QSpinBox(self.rule_group)
        self.start_index.setObjectName(u"start_index")
        self.start_index.setMinimum(1)
        self.start_index.setMaximum(999999)
        self.digits_label = QLabel(self.rule_group)
        self.digits_label.setObjectName(u"digits_label")
        self.digits = QSpinBox(self.rule_group)
        self.digits.setObjectName(u"digits")
        self.digits.setMinimum(1)
        self.digits.setMaximum(10)
        self.rule_preview_label = QLabel(self.rule_group)
        self.rule_preview_label.setObjectName(u"rule_preview_label")
        self.rule_preview = QLabel(self.rule_group)
        self.rule_preview.setObjectName(u"rule_preview")
        self.rule_preview.setMinimumHeight(28)
        self.ruleLayout.setWidget(0, QFormLayout.LabelRole, self.prefix_label)
        self.ruleLayout.setWidget(0, QFormLayout.FieldRole, self.prefix)
        self.ruleLayout.setWidget(1, QFormLayout.LabelRole, self.start_index_label)
        self.ruleLayout.setWidget(1, QFormLayout.FieldRole, self.start_index)
        self.ruleLayout.setWidget(2, QFormLayout.LabelRole, self.digits_label)
        self.ruleLayout.setWidget(2, QFormLayout.FieldRole, self.digits)
        self.ruleLayout.setWidget(3, QFormLayout.LabelRole, self.rule_preview_label)
        self.ruleLayout.setWidget(3, QFormLayout.FieldRole, self.rule_preview)
        self.buttonLayout = QHBoxLayout()
        self.buttonLayout.setObjectName(u"buttonLayout")
        self.buttonLayout.addStretch()
        self.preview_button = QPushButton(self.centralwidget)
        self.preview_button.setObjectName(u"preview_button")
        self.execute_button = QPushButton(self.centralwidget)
        self.execute_button.setObjectName(u"execute_button")
        self.buttonLayout.addWidget(self.preview_button)
        self.buttonLayout.addWidget(self.execute_button)
        self.preview_group = QGroupBox(self.centralwidget)
        self.preview_group.setObjectName(u"preview_group")
        self.previewLayout = QGridLayout(self.preview_group)
        self.previewLayout.setObjectName(u"previewLayout")
        self.preview_table = QTableWidget(self.preview_group)
        self.preview_table.setObjectName(u"preview_table")
        self.preview_table.setColumnCount(3)
        self.preview_table.setRowCount(0)
        self.preview_table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.preview_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.preview_table.setAlternatingRowColors(True)
        self.preview_table.verticalHeader().setVisible(False)
        self.preview_table.horizontalHeader().setStretchLastSection(False)
        self.preview_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.Stretch)
        self.preview_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.Stretch)
        self.preview_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeToContents)
        self.previewLayout.addWidget(self.preview_table, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.folder_group, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.rule_group, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.buttonLayout, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.preview_group, 3, 0, 1, 1)
        BatchRenameWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QStatusBar(BatchRenameWindow)
        self.statusBar.setObjectName(u"statusBar")
        BatchRenameWindow.setStatusBar(self.statusBar)

        self.retranslateUi(BatchRenameWindow)

        QMetaObject.connectSlotsByName(BatchRenameWindow)

    def retranslateUi(self, BatchRenameWindow):
        BatchRenameWindow.setWindowTitle(QCoreApplication.translate("BatchRenameWindow", u"图片批量重命名", None))
        self.folder_group.setTitle(QCoreApplication.translate("BatchRenameWindow", u"文件夹", None))
        self.folder_path.setPlaceholderText(QCoreApplication.translate("BatchRenameWindow", u"请选择包含图片的文件夹", None))
        self.select_folder.setText(QCoreApplication.translate("BatchRenameWindow", u"选择文件夹", None))
        self.rule_group.setTitle(QCoreApplication.translate("BatchRenameWindow", u"重命名规则", None))
        self.prefix_label.setText(QCoreApplication.translate("BatchRenameWindow", u"文件名前缀", None))
        self.start_index_label.setText(QCoreApplication.translate("BatchRenameWindow", u"起始编号", None))
        self.digits_label.setText(QCoreApplication.translate("BatchRenameWindow", u"编号位数", None))
        self.rule_preview_label.setText(QCoreApplication.translate("BatchRenameWindow", u"规则预览", None))
        self.rule_preview.setText(QCoreApplication.translate("BatchRenameWindow", u"未生成预览", None))
        self.preview_button.setText(QCoreApplication.translate("BatchRenameWindow", u"预览重命名", None))
        self.execute_button.setText(QCoreApplication.translate("BatchRenameWindow", u"执行重命名", None))
        self.preview_group.setTitle(QCoreApplication.translate("BatchRenameWindow", u"预览结果", None))
        self.preview_table.setHorizontalHeaderLabels([
            QCoreApplication.translate("BatchRenameWindow", u"原文件名", None),
            QCoreApplication.translate("BatchRenameWindow", u"新文件名", None),
            QCoreApplication.translate("BatchRenameWindow", u"状态", None)
        ])
