from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(1140, 857)
        icon = QIcon()
        icon.addFile(u":/tool_icon/resource/main.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.shake_tool = QAction(MainWindow)
        self.shake_tool.setObjectName(u"shake_tool")
        self.imageeditor = QAction(MainWindow)
        self.imageeditor.setObjectName(u"imageeditor")
        self.batch_rename = QAction(MainWindow)
        self.batch_rename.setObjectName(u"batch_rename")
        self.about = QAction(MainWindow)
        self.about.setObjectName(u"about")
        self.rawimageeditor = QAction(MainWindow)
        self.rawimageeditor.setObjectName(u"rawimageeditor")
        self.video_compare = QAction(MainWindow)
        self.video_compare.setObjectName(u"video_compare")
        self.pqtools2code = QAction(MainWindow)
        self.pqtools2code.setObjectName(u"pqtools2code")
        self.field_depth_tool = QAction(MainWindow)
        self.field_depth_tool.setObjectName(u"field_depth_tool")
        self.af_calc_tool = QAction(MainWindow)
        self.af_calc_tool.setObjectName(u"af_calc_tool")
        self.userguide = QAction(MainWindow)
        self.userguide.setObjectName(u"userguide")
        self.clearcache = QAction(MainWindow)
        self.clearcache.setObjectName(u"clearcache")
        self.checkupdate = QAction(MainWindow)
        self.checkupdate.setObjectName(u"checkupdate")
        self.yuv_viewer = QAction(MainWindow)
        self.yuv_viewer.setObjectName(u"yuv_viewer")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.mdiArea = QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName(u"mdiArea")
        self.mdiArea.setAcceptDrops(True)
        self.mdiArea.setLineWidth(0)
        self.mdiArea.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.mdiArea.setViewMode(QMdiArea.TabbedView)
        self.mdiArea.setTabsClosable(True)
        self.mdiArea.setTabsMovable(True)
        self.mdiArea.setTabShape(QTabWidget.Rounded)

        self.gridLayout_2.addWidget(self.mdiArea, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1140, 22))
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        self.menuISP = QMenu(self.menubar)
        self.menuISP.setObjectName(u"menuISP")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menuISP.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menu_2.addAction(self.shake_tool)
        self.menu_2.addAction(self.imageeditor)
        self.menu_2.addAction(self.batch_rename)
        self.menu_2.addAction(self.rawimageeditor)
        self.menu_2.addAction(self.video_compare)
        self.menu_2.addAction(self.yuv_viewer)
        self.menuISP.addAction(self.pqtools2code)
        self.menuISP.addAction(self.field_depth_tool)
        self.menu.addAction(self.userguide)
        self.menu.addAction(self.clearcache)
        self.menu.addAction(self.checkupdate)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"ImageTools", None))
        self.shake_tool.setText(QCoreApplication.translate("MainWindow", u"抖动测试工具", None))
        self.imageeditor.setText(QCoreApplication.translate("MainWindow", u"图片分析工具", None))
        self.batch_rename.setText(QCoreApplication.translate("MainWindow", u"图片批量重命名", None))
        self.about.setText(QCoreApplication.translate("MainWindow", u"关于", None))
        self.rawimageeditor.setText(QCoreApplication.translate("MainWindow", u"raw图分析工具", None))
        self.video_compare.setText(QCoreApplication.translate("MainWindow", u"视频对比工具", None))
        self.pqtools2code.setText(QCoreApplication.translate("MainWindow", u"PQtools转代码", None))
        self.field_depth_tool.setText(QCoreApplication.translate("MainWindow", u"镜头计算器", None))
        self.af_calc_tool.setText(QCoreApplication.translate("MainWindow", u"镜头曲线计算工具", None))
        self.userguide.setText(QCoreApplication.translate("MainWindow", u"用户手册", None))
        self.clearcache.setText(QCoreApplication.translate("MainWindow", u"清理缓存", None))
        self.checkupdate.setText(QCoreApplication.translate("MainWindow", u"检查更新", None))
        self.yuv_viewer.setText(QCoreApplication.translate("MainWindow", u"YUV查看工具", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"工具", None))
        self.menuISP.setTitle(QCoreApplication.translate("MainWindow", u"ISP", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"关于", None))
